# Generated by Django 5.2 on 2026-04-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_demo_link',
        ),
    ]
