# Generated by Django 5.2 on 2026-04-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_address_profile_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='achievements/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Achievements',
                'ordering': ['order'],
            },
        ),
    ]
