# Generated by Django 5.2 on 2026-04-02 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='image',
        ),
        migrations.CreateModel(
            name='AchievementImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='achievements/')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.achievement')),
            ],
        ),
    ]
